services:
  mongodb:
    image: mongo:7.0
    container_name: harbour-space-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: harbour-space
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - harbour-space-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  harbour-space-network:
    driver: bridge
